### cadastrar (signUp)
POST http://localhost:3000/auth/signup
Content-Type: application/json

{
  "email": "teste@exemplo.com",
  "password": "senha123",
  "firstName": "João",
  "lastName": "Silva"
}


### logar (signIn)
POST http://localhost:3000/auth/signin
Content-Type: application/json

{
  "email": "teste@exemplo.com",
  "password": "senha123"
}